### ISSUE TITLE
Training base

### ISSUE THREAD

**Issue by escudero** [Aalawani686/Company-Logo-CNN-Classification#1]
Hi,
I liked your project.
Do you still have the training base (images)?
I am trying to replicate your project to reference a research I am doing.

Thank you.

**Comment by Aalawani686** [comment]
Hi,

I used the Flickr logos dataset.
http://image.ntua.gr/iva/datasets/flickr_logos/
Hope this helps.

**Comment by escudero** [comment]
Thanks
